### ISSUE TITLE
Virtual-Kubelet Metrics

### ISSUE THREAD

**Issue by Smithx10** [virtual-kubelet/virtual-kubelet#418] opened 2018-11-22 16:04 UTC
VKubelet should report metrics about itself,  preferably via Prometheus.

**Comment by rbitia** [comment] 2018-11-30 00:22
VK reports metrics through the metrics server api, is that what you are looking for? VK itself is a pod that looks like a node so you can't get metrics from the node itself.

**Comment by Smithx10** [comment] 2018-11-30 01:09
In my use case I will not be scheduling VK via Kubernetes.  

I was hoping that there were some kind of VKubelet Internal Metrics that we would want to make available to operators.  Information about the run-time, and the application etc.

I am not referring to instances scheduled by VK, but rather VK itself.

For example:
![metrics](https://user-images.githubusercontent.com/12032554/49262038-b51d8700-f412-11e8-9b6a-98727cf996b9.png)

**Comment by cpuguy83** [comment] 2018-11-30 05:31
+1 for metrics.
We have tracing in but have not done metrics yet as deciding what to track and how will take some thought.

**Comment by myechuri** [comment] 2020-02-19 19:05
@cpuguy83 : is this issue still relevant? If so, i'd be happy to pick it up. Thanks!

**Comment by cpuguy83** [comment] 2020-02-19 19:50
It is still relevant.
Ideally it would find a nice home like we have for the tracing package.

**Comment by myechuri** [comment] 2020-02-19 19:54
Great, thanks @cpuguy83 . Let me pick this up.

**Comment by myechuri** [comment] 2020-02-19 19:57
@rbitia : just noticed that the issue is assigned to you - want to confirm that you are not looking into it before assigning it to self. Can you please let me know? Thanks!

**Comment by cpuguy83** [comment] 2020-02-19 20:02
I don't think anyone is looking into this yet.

**Comment by myechuri** [comment] 2020-02-19 20:14
Thanks, @cpuguy83 . Assigned to self.

**Comment by myechuri** [comment] 2020-03-02 21:04
Have scaffolding in place for metrics and want to run it by @cpuguy83 to see if i am on the right track. Here are the details:

1) [OpenMetrics](https://github.com/OpenObservability/OpenMetrics) is not yet ready for consumption, so, went with Prometheus go-client.

2) Draft for plumbing first set of metrics (basic golang runtime metrics, as suggested in [this comment](https://github.com/virtual-kubelet/virtual-kubelet/issues/418#issuecomment-443053509) ): [https://github.com/virtual-kubelet/virtual-kubelet/commit/365f25f1f971b99db21f41c6e07957624d7ef5fa](https://github.com/virtual-kubelet/virtual-kubelet/commit/365f25f1f971b99db21f41c6e07957624d7ef5fa). @cpuguy83 , does this look like a good starting point?

3) Testing done:
- Created minikube cluster
- Started vk with mock provider
```
KUBELET_PORT=10250 ./bin/virtual-kubelet --nodename vkubelet-mo-0 --provider mock --provider-config ./hack/skaffold/virtual-kubelet/vkubelet-mock-0-cfg.json --startup-timeout 10s --klog.v "2" --klog.logtostderr --log-level debug 
```
```
# kubectl get nodes
NAME              STATUS   ROLES    AGE   VERSION
ip-172-31-71-50   Ready    master   13d   v1.17.2
vkubelet-mock-0   Ready    agent    13d   v1.15.2-vk-v1.2.0-13-geca2098-dev
```
- Curled `vk-metrics` endpoint:
```
# curl http://172.31.71.50:10300/vk-metrics
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6157    0  6157    0     0  3953k      0 --:--:-- --:--:-- --:--:-- 6012k
# HELP go_gc_duration_seconds A summary of the GC invocation durations.
# TYPE go_gc_duration_seconds summary
go_gc_duration_seconds{quantile="0"} 2.0986e-05
go_gc_duration_seconds{quantile="0.25"} 2.7725e-05
go_gc_duration_seconds{quantile="0.5"} 3.5193e-05
go_gc_duration_seconds{quantile="0.75"} 4.6116e-05
go_gc_duration_seconds{quantile="1"} 4.6116e-05
go_gc_duration_seconds_sum 0.00013002
go_gc_duration_seconds_count 4
# HELP go_goroutines Number of goroutines that currently exist.
# TYPE go_goroutines gauge
go_goroutines 80
# HELP go_info Information about the Go environment.
# TYPE go_info gauge
go_info{version="go1.13.8"} 1
# HELP go_memstats_alloc_bytes Number of bytes allocated and still in use.
# TYPE go_memstats_alloc_bytes gauge
go_memstats_alloc_bytes 4.914112e+06
# HELP go_memstats_alloc_bytes_total Total number of bytes allocated, even if freed.
# TYPE go_memstats_alloc_bytes_total counter
go_memstats_alloc_bytes_total 1.2354312e+07
# HELP go_memstats_buck_hash_sys_bytes Number of bytes used by the profiling bucket hash table.
# TYPE go_memstats_buck_hash_sys_bytes gauge
go_memstats_buck_hash_sys_bytes 1.44673e+06
# HELP go_memstats_frees_total Total number of frees.
# TYPE go_memstats_frees_total counter
go_memstats_frees_total 108122
# HELP go_memstats_gc_cpu_fraction The fraction of this program's available CPU time used by the GC since the program started.
# TYPE go_memstats_gc_cpu_fraction gauge
go_memstats_gc_cpu_fraction 0.00018832946144786114
# HELP go_memstats_gc_sys_bytes Number of bytes used for garbage collection system metadata.
# TYPE go_memstats_gc_sys_bytes gauge
go_memstats_gc_sys_bytes 2.418688e+06
# HELP go_memstats_heap_alloc_bytes Number of heap bytes allocated and still in use.
# TYPE go_memstats_heap_alloc_bytes gauge
go_memstats_heap_alloc_bytes 4.914112e+06
# HELP go_memstats_heap_idle_bytes Number of heap bytes waiting to be used.
# TYPE go_memstats_heap_idle_bytes gauge
go_memstats_heap_idle_bytes 5.9416576e+07
# HELP go_memstats_heap_inuse_bytes Number of heap bytes that are in use.
# TYPE go_memstats_heap_inuse_bytes gauge
go_memstats_heap_inuse_bytes 6.774784e+06
# HELP go_memstats_heap_objects Number of allocated objects.
# TYPE go_memstats_heap_objects gauge
go_memstats_heap_objects 45300
# HELP go_memstats_heap_released_bytes Number of heap bytes released to OS.
# TYPE go_memstats_heap_released_bytes gauge
go_memstats_heap_released_bytes 5.9383808e+07
# HELP go_memstats_heap_sys_bytes Number of heap bytes obtained from system.
# TYPE go_memstats_heap_sys_bytes gauge
go_memstats_heap_sys_bytes 6.619136e+07
# HELP go_memstats_last_gc_time_seconds Number of seconds since 1970 of last garbage collection.
# TYPE go_memstats_last_gc_time_seconds gauge
go_memstats_last_gc_time_seconds 1.5831789533211129e+09
# HELP go_memstats_lookups_total Total number of pointer lookups.
# TYPE go_memstats_lookups_total counter
go_memstats_lookups_total 0
# HELP go_memstats_mallocs_total Total number of mallocs.
# TYPE go_memstats_mallocs_total counter
go_memstats_mallocs_total 153422
# HELP go_memstats_mcache_inuse_bytes Number of bytes in use by mcache structures.
# TYPE go_memstats_mcache_inuse_bytes gauge
go_memstats_mcache_inuse_bytes 3472
# HELP go_memstats_mcache_sys_bytes Number of bytes used for mcache structures obtained from system.
# TYPE go_memstats_mcache_sys_bytes gauge
go_memstats_mcache_sys_bytes 16384
# HELP go_memstats_mspan_inuse_bytes Number of bytes in use by mspan structures.
# TYPE go_memstats_mspan_inuse_bytes gauge
go_memstats_mspan_inuse_bytes 91936
# HELP go_memstats_mspan_sys_bytes Number of bytes used for mspan structures obtained from system.
# TYPE go_memstats_mspan_sys_bytes gauge
go_memstats_mspan_sys_bytes 98304
# HELP go_memstats_next_gc_bytes Number of heap bytes when next garbage collection will take place.
# TYPE go_memstats_next_gc_bytes gauge
go_memstats_next_gc_bytes 6.566e+06
# HELP go_memstats_other_sys_bytes Number of bytes used for other system allocations.
# TYPE go_memstats_other_sys_bytes gauge
go_memstats_other_sys_bytes 705966
# HELP go_memstats_stack_inuse_bytes Number of bytes in use by the stack allocator.
# TYPE go_memstats_stack_inuse_bytes gauge
go_memstats_stack_inuse_bytes 884736
# HELP go_memstats_stack_sys_bytes Number of bytes obtained from system for stack allocator.
# TYPE go_memstats_stack_sys_bytes gauge
go_memstats_stack_sys_bytes 884736
# HELP go_memstats_sys_bytes Number of bytes obtained from system.
# TYPE go_memstats_sys_bytes gauge
go_memstats_sys_bytes 7.1762168e+07
# HELP go_threads Number of OS threads created.
# TYPE go_threads gauge
go_threads 9
# HELP process_cpu_seconds_total Total user and system CPU time spent in seconds.
# TYPE process_cpu_seconds_total counter
process_cpu_seconds_total 0.13
# HELP process_max_fds Maximum number of open file descriptors.
# TYPE process_max_fds gauge
process_max_fds 1024
# HELP process_open_fds Number of open file descriptors.
# TYPE process_open_fds gauge
process_open_fds 9
# HELP process_resident_memory_bytes Resident memory size in bytes.
# TYPE process_resident_memory_bytes gauge
process_resident_memory_bytes 2.994176e+07
# HELP process_start_time_seconds Start time of the process since unix epoch in seconds.
# TYPE process_start_time_seconds gauge
process_start_time_seconds 1.58317893233e+09
# HELP process_virtual_memory_bytes Virtual memory size in bytes.
# TYPE process_virtual_memory_bytes gauge
process_virtual_memory_bytes 1.38461184e+08
# HELP process_virtual_memory_max_bytes Maximum amount of virtual memory available in bytes.
# TYPE process_virtual_memory_max_bytes gauge
process_virtual_memory_max_bytes -1
# HELP promhttp_metric_handler_requests_in_flight Current number of scrapes being served.
# TYPE promhttp_metric_handler_requests_in_flight gauge
promhttp_metric_handler_requests_in_flight 1
# HELP promhttp_metric_handler_requests_total Total number of scrapes by HTTP status code.
# TYPE promhttp_metric_handler_requests_total counter
promhttp_metric_handler_requests_total{code="200"} 2
promhttp_metric_handler_requests_total{code="500"} 0
promhttp_metric_handler_requests_total{code="503"} 0
```
4) If above looks ok, will cleanup and prepare PR. Would love to expand beyond golang metrics in a followup PR. A lot of k8s events recorded in pod controller (ex: [this event](https://github.com/virtual-kubelet/virtual-kubelet/blob/0bdf7423037e0ccefb794c8b5f570137c65ce864/node/pod.go#L92), and other pod start/stop/update/delete success/failure events) would be interesting counters to add next. @Smithx10 : does this align with what you were hoping to see?

**Comment by cpuguy83** [comment] 2020-03-02 23:54
It's a start to at least get something out, but I'm not sure there is much value in adding it to the daemon being built from cmd here since that's only used for testing.

I would use the opencensus prom exporter here since we are already using opencensus for tracing.

**Comment by myechuri** [comment] 2020-03-03 00:23
Thanks for the quick and helpful feedback, @cpuguy83 !

> It's a start to at least get something out, but I'm not sure there is much value in adding it to the daemon being built from cmd here since that's only used for testing.

Got it, thanks for clarifying. i was not aware that daemon built here is only used for testing. Let me look through tracing one more time to see if there is a way to have metrics as a common functionality across vk built via all providers.

> I would use the opencensus prom exporter here since we are already using opencensus for tracing.

Makes sense. Let me rework to use opencensus prom exporter and ping when ready. Thanks!

**Comment by cpuguy83** [comment] 2020-03-03 00:56
@myechuri Publishing the metrics to an HTTP endpoint can be configured here, which some providers use: https://github.com/virtual-kubelet/node-cli/

However the real power will come from being able to integrate metrics produced by the VK runtime into consumers of the VK library.

**Comment by myechuri** [comment] 2020-03-03 01:51
> Publishing the metrics to an HTTP endpoint can be configured here, which some providers use: https://github.com/virtual-kubelet/node-cli/

Thanks! Elotl's provider (to be open sourced soon) is using above as well:

```
node, err := cli.New(ctx,
		cli.WithBaseOpts(o),
		cli.WithCLIVersion(buildVersion, buildTime),
		cli.WithProvider("cloud-instance-provider",
			func(cfg provider.InitConfig) (provider.Provider, error) {
 ...
```

> However the real power will come from being able to integrate metrics produced by the VK runtime into consumers of the VK library.

Agree 100%. It would be great to VK metrics out of the box for consumers of the VK library. Let me play around a bit and report back in a week. Thanks again for the helpful guidance, @cpuguy83 !

**Comment by cwdsuzhou** [comment] 2020-03-10 04:59
Is this work still in progress ?

**Comment by myechuri** [comment] 2020-03-10 05:18
> Is this work still in progress ?

@cwdsuzhou : yes, i'll share status update by the end of week. Thanks!

**Comment by pires** [comment] 2021-01-29 00:10
@myechuri I'm assuming you didn't get a chance to finish what you were working on, were you? Need help?

**Comment by cpuguy83** [comment] 2022-06-23 17:45
Talking about this on the on the VK community call:

We should probably add opentelemetry support (and replace/augment existing opencensus support) to track the metrics.
Potentially we could add a way to attach a metrics HTTP handler to VK's HTTP server (optionally).

**Comment by helayoty** [comment] 2023-04-06 15:35
Opentelemetry is already supported now.

**Closed by helayoty** 2023-04-06 15:35 UTC
Labels: enhancement, help wanted
