### ISSUE TITLE
Print "open : no such file or directory" when create VK node

### ISSUE THREAD

**Issue by lioncruise** [virtual-kubelet/virtual-kubelet#203] opened 2018-05-17 13:25 UTC
---

### Environment summary

Provider (e.g. ACI, AWS Fargate, Hyper)

AliCloud ECS

Version (e.g. 0.1, 0.2-beta)

latest version

K8s Master Info (e.g. AKS, ACS, Bare Metal, EKS)

1.8.4 installed by kubeadm

### Issue Details

When I start a VK node with mock provider, it always prints a message "open : no such file or directory" as following. The debug message is written by me to locate this problem.

```shell
[root@slave virtual-kubelet]# ./bin/virtual-kubelet  --provider mock
2018/05/17 21:02:49 Node 'virtual-kubelet--1' with OS type 'Linux' registered
[DEBUG] >>>>>>>
2018/05/17 21:02:49 open : no such file or directory
[DEBUG] <<<<<<<
2018/05/17 21:02:50 receive CreatePod "calico-node-cw2hq"
2018/05/17 21:02:50 Pod 'calico-node-cw2hq' created.
2018/05/17 21:02:50 receive CreatePod "kube-state-metrics-77c66586cb-tg8p8"
2018/05/17 21:02:50 Pod 'kube-state-metrics-77c66586cb-tg8p8' created.
2018/05/17 21:02:50 receive CreatePod "nfs-client-provisioner-b7749dd5f-7mztz"
2018/05/17 21:02:50 Pod 'nfs-client-provisioner-b7749dd5f-7mztz' created.
2018/05/17 21:02:50 receive CreatePod "prometheus-0"
2018/05/17 21:02:50 Pod 'prometheus-0' created.
2018/05/17 21:02:50 receive CreatePod "node-problem-detector-v0.1-ql55n"
2018/05/17 21:02:50 Pod 'node-problem-detector-v0.1-ql55n' created.
2018/05/17 21:02:50 receive CreatePod "alertmanager-877ccbc6d-gv68n"
2018/05/17 21:02:50 Pod 'alertmanager-877ccbc6d-gv68n' created.
2018/05/17 21:02:50 receive CreatePod "calico-kube-controllers-6bc456bbf4-68scg"
2018/05/17 21:02:50 Pod 'calico-kube-controllers-6bc456bbf4-68scg' created.
2018/05/17 21:02:50 receive CreatePod "kube-proxy-xbx7t"
2018/05/17 21:02:50 Pod 'kube-proxy-xbx7t' created.
2018/05/17 21:02:50 receive CreatePod "node-exporter-j2zcc"
2018/05/17 21:02:50 Pod 'node-exporter-j2zcc' created.
```

Finally, I found the problem at `Run()` function in `vkubelet/vkubelet.go`. I am curious why this line can print "open : no such file or directory" and I can't find fix the problem by myself. And I'm not sure this problem is just happening on my machine or it is a common problem. I will be very grateful if you find the reason and solve this problem. 

```go
func (s *Server) Run() error {
	sig := make(chan os.Signal, 1)
	signal.Notify(sig, syscall.SIGINT, syscall.SIGTERM)
	go func() {
		<-sig
		s.Stop()
	}()

	opts := metav1.ListOptions{
		FieldSelector: fields.OneTermEqualSelector("spec.nodeName", s.nodeName).String(),
	}

	fmt.Println("[DEBUG] >>>>>>>")
	pods, err := s.k8sClient.CoreV1().Pods(s.namespace).List(opts)  // problem is at this line!!!
	fmt.Println("[DEBUG] <<<<<<<")
	if err != nil {
		log.Fatal(err)
	}
	s.resourceManager.SetPods(pods)
	s.reconcile()
```

**Comment by d-nishi** [comment] 2018-05-18 08:00
@rbitia  this is an error within virtual-kubelet but not specific to --provider aws rather --provider mock that simulates the expected behavior on the client side. I am looking at this but just want to confirm if the "label" reflects a provider error or if it reflects who is assigned to the bug?

@lioncruise looking at the problem - will revert!

**Comment by d-nishi** [comment] 2018-05-21 01:00
Thanks @ofiliz for removing aws label

**Comment by rbitia** [comment] 2018-05-22 03:37
ah yeah I thought it was a provider specific one so ignore that label :)

**Comment by d-nishi** [comment] 2018-05-22 06:55
@rbitia thats fine! 

@lioncruise this is not happening because of Run() function in vkubelet.go file
It is happening when the mock provider tries to run `go ApiServerStart(p)` here: https://github.com/virtual-kubelet/virtual-kubelet/blob/master/vkubelet/vkubelet.go#L125 

1. Lets prove this 1st. I am using virtual-kubelet release v0.2-beta-11
Modify the cmd/root.go file here and make build. Then run ./bin/virtual-kubelet --provider mock

```
var RootCmd = &cobra.Command{
        Use:   "virtual-kubelet",
        Short: "virtual-kubelet provides a virtual kubelet interface for your kubernetes cluster.",
        Long: `virtual-kubelet implements the Kubelet interface with a pluggable
backend implementation allowing users to create kubernetes nodes without running the kubelet.
This allows users to schedule kubernetes workloads on nodes that aren't running Kubernetes.`,
        Run: func(cmd *cobra.Command, args []string) {
                time.Sleep(1 * time.Second)
                fmt.Println("$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$")

                fmt.Println(kubeConfig)
                f, err := vkubelet.New(nodeName, operatingSystem, kubeNamespace, kubeConfig, taint, provider, providerConfig)
                if err != nil {
                        log.Fatal(err)
                }
                time.Sleep(1 * time.Second)
                fmt.Println("==================================================")

                f.Run()
        },
}
```

Output will be visible as follows:
```
dnishi$ ./bin/virtual-kubelet --provider mock
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
/Users/dnishi/.kube/config
2018/05/21 22:38:30 Node 'virtual-kubelet' with OS type 'Linux' registered
2018/05/21 22:38:30 open : no such file or directory
==================================================
2018/05/21 22:38:31 receive GetPods
2018/05/21 22:38:44 receive GetPods
```

You will notice the line ==================== comes after the error message you found `open : no such file or directory`

2. I debugged more and realized the error was happening right above this line: https://github.com/virtual-kubelet/virtual-kubelet/blob/master/vkubelet/vkubelet.go#L127 - naturally this led me to apiserver.go file and specifically `ApiserverStart(provider Provider)` function where post some more experiments, I added an additional print statement `log.Printf("http.ListenAndServeTLS: %s\n", err)` above this line: https://github.com/virtual-kubelet/virtual-kubelet/blob/master/vkubelet/apiserver.go#L34

Output seen:
```
dnishi$ ./bin/virtual-kubelet --provider mock
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
/Users/dnishi/.kube/config
2018/05/21 23:03:38 Node 'virtual-kubelet' with OS type 'Linux' registered
2018/05/21 23:03:38 http.ListenAndServeTLS: open : no such file or directory
2018/05/21 23:03:38 open : no such file or directory
==================================================
2018/05/21 23:03:39 receive GetPods
```

Please reproduce and confirm you see the same flow as me - I would like to investigate the mock provider design and potentially improve it for others. 

@robbiezhang - FYI.

**Comment by robbiezhang** [comment] 2018-05-23 19:22
Similar to #88 and related to #156. The VK needs a SSL certificate to start the "apiserver" to serve the interactive requests from kube-apiserver, i.e. logs, exec, attach, etc. As we tested, a self-signed certificate will work, if kube-apiserver doesn't turn on the TLS validation. Otherwise, you need to give a certificate signed by the ca of the cluster. Close as a dup.

**Closed by robbiezhang** 2018-05-23 19:22 UTC
Labels: bug

**Comment by mqliang** [comment] 2018-07-08 22:03
@d-nishi 
Hi.

I meet the same issue. However, it seems that it is NOT because the mock provider tries to run `go ApiServerStart(p)` here https://github.com/virtual-kubelet/virtual-kubelet/blob/master/vkubelet/vkubelet.go#L147

I tried to modify the code as:
```
if provider != "mock" {
		go ApiserverStart(p)
	}
```
So if provider is mock, it will not  run `go ApiserverStart(p)`. But the error log still there.
