### ISSUE TITLE
Controlling ACI instance size

### ISSUE THREAD

**Issue by brobichaud** [virtual-kubelet/virtual-kubelet#144] opened 2018-04-18 21:44 UTC
---

### Environment summary
ACS cluster with Windows nodes, k8s v1.7.7-7. Windows Server 2016 RTM.

Provider (e.g. Azure, Hyper)
Azure

Version (e.g. 0.1, 0.2-beta)
microsoft/aci-connector-k8s:canary

K8s Master Info (e.g. AKS, ACS, Bare Metal)
ACS

Install Method (e.g. Helm Chart, )
kubectl & yaml

### Issue Details
I'm trying to get a larger ACI instance size. It seems to always default to 1Core and 1.5GB RAM.

### Repo Steps
Deploy a pod, specify either resource requests or limits or both. No change in ACI instance size. Example yaml:
          resources:
            requests:
              cpu: 2000m
              memory: 4Gi
            limits:
              cpu: 4000m
              memory: 14Gi

**Comment by robbiezhang** [comment] 2018-04-18 22:47
@brobichaud, please use microsoft/virtual-kubelet:latest as the image.
Please use G as the unit of the memory instead of Gi

**Comment by robbiezhang** [comment] 2018-04-19 21:54
@brobichaud I assume you have figured it out. Close it now. If you any questions, feel free to open issues.

**Closed by robbiezhang** 2018-04-19 21:54 UTC

**Comment by brobichaud** [comment] 2018-04-19 23:44
I was able to work around this as you can see in #143. But should this be considered a bug since it doesn't follow the k8s pod spec (G vs Gi)?

**Comment by robbiezhang** [comment] 2018-04-20 01:38
Unfortunately, this is by design, as ACI doesn't want to too many fragments.
