### ISSUE TITLE
Pod scheduled at Windows kubelet should not mount any secret volume

### ISSUE THREAD

**Issue by sioakim** [virtual-kubelet/virtual-kubelet#40] opened 2017-12-22 21:31 UTC
[error.log](https://github.com/virtual-kubelet/virtual-kubelet/files/1583501/error.log)
I use the attached xml to deploy to Windows kubelet.

The windows kubelet should accept nodes for "beta.kubernetes.io/os": "windows"

From "describe node I get:"
Labels:             beta.kubernetes.io/os=windows

I get error:
No nodes are available that match all of the following predicates:: MatchNodeSelector (2), PodToleratesNodeTaints (1).

Full info is attached.

**Comment by sioakim** [comment] 2017-12-22 21:38
FYI - i just replaced the attached xml with nginx and Linux and worked instantly.

**Comment by robbiezhang** [comment] 2017-12-22 22:17
@sioakim, can you double check the Linux pod runs on the virtual-kubelet for Linux?

The virtual-kubelet node has the taints "azure.com/aci:NoSchedule". If you want to schedule a pod to the virtual-kubelet, you need to add the following tolerations to your pod spec:

  tolerations:
  - key: azure.com/aci
    effect: NoSchedule

Seems like the example is missing this section. I'll update it.

**Comment by sioakim** [comment] 2017-12-22 23:20
You are right - the linux one started on the k8s node. I had some other example apparently that had started it on the ACI.

Can you please provide an example for Windows as well?

The below doesn't work for example:

```
apiVersion: v1
kind: Pod
metadata:
  name: iis
spec:
  containers:
  - image: microsoft/iis
    imagePullPolicy: Always
    name: iis
    resources:
      requests:
        memory: 4G
        cpu: 2
    ports:
    - containerPort: 80
      name: http
      protocol: TCP
    - containerPort: 443
      name: https
  dnsPolicy: ClusterFirst
  nodeName: virtual-kubelet-aciconnector-win
  tolerations:
  - key: azure.com/aci
    effect: NoSchedule
```

**Comment by sioakim** [comment] 2017-12-23 08:12
Specifically the error for the above is:

2017/12/23 08:11:18 Error creating pod 'iis': api call to https://management.azure.com/subscriptions/9debe65e-7de1-48d8-9b1b-c22d8ef23c75/resourceGroups/SI-Containers/providers/Microsoft.ContainerInstance/containerGroups/default-iis?api-version=2017-12-01-preview: got HTTP response status code 400 error code "SecretVolumesNotSupportedInWindows": Secret volumes are not supported for Windows containers.

**Comment by sioakim** [comment] 2017-12-27 09:21
Updated to 1.8.2 (from 1.7.7) and the issue still persists.
I haven't been able to schedule a Windows container.

Anyone has been successful with Windows containers or no one has tried it?

**Comment by robbiezhang** [comment] 2017-12-27 23:28
@sioakim, short answer: you can add `automountServiceAccountToken: false` into your pod spec to workaround the issue.

The root cause is that k8s doesn't support secret volume for Windows. So, ACI forbids it in the API. However, the virtual-kubelet simulates the default service account for pod by using the secret volume. This is a bug in the ACI provider. I'll update the title to track it.

**Comment by robbiezhang** [comment] 2017-12-27 23:35
Upload the [example](https://raw.githubusercontent.com/virtual-kubelet/virtual-kubelet/master/examples/nginx-pod.yaml). It works for me.

**Comment by sioakim** [comment] 2018-01-03 07:45
Thank you - works with the workaround.

**Comment by robbiezhang** [comment] 2018-01-22 19:38
Close the issue, as the fix is merged. Plan to release in v0.2

**Closed by robbiezhang** 2018-01-22 19:38 UTC
Labels: bug

**Comment by dylanjohnsonsfo** [comment] 2019-03-14 19:24
automountServiceAccountToken: false doesn't work for me , its the istio-sidecar that is  throwing the error regarding.

```HTTP response status code 400 error code "SecretVolumesNotSupportedOnWindows" ```
