### ISSUE TITLE
AKS Connector KubeDNS Resolution and Service IP resolution is not working (Windows Containers)

### ISSUE THREAD

**Issue by Void-Barrie** [virtual-kubelet/virtual-kubelet#546] opened 2019-03-25 21:27 UTC
---

### Environment summary

Provider (e.g. ACI, AWS Fargate)
AKS / ACI

Version (e.g. 0.1, 0.2-beta)
1.12.6

K8s Master Info (e.g. AKS, ACS, Bare Metal, EKS)
AKS (US West 2)

Install Method (e.g. Helm Chart, )
Helm (https://docs.microsoft.com/en-us/azure/aks/virtual-kubelet)

### Issue Details
I would expect that windows containers running on ACI instances via Virtual Kublet would be able to resolve K8s service DNS entries.

ACI windows instances do not appear to use the K8s subnet, nor the K8s dns. I cannot resolve service names from inside the Windows container, nor can I connect to K8s service IPs from the windows ACI container

Workarounds referred in the other tickets do not seem to apply to Windows ACI instances or containers. 
(https://github.com/virtual-kubelet/virtual-kubelet/blob/master/providers/azure/README.md#create-an-aks-cluster-with-vnet)

### Repo Steps
Create AKS cluster with Advanced Networking enabled
Add Virtual Kublet via (https://docs.microsoft.com/en-us/azure/aks/virtual-kubelet)
Deploy a service
Deploy a windows pod
Note windows containers cannot ping service cluster IP, nor resolve service DNS

Remove helm virtual kublet
Install virtual kublet and subnet via az CLI according to: https://github.com/virtual-kubelet/virtual-kubelet/blob/master/providers/azure/README.md#create-an-aks-cluster-with-vnet
Deploy windows pod.
Note windows pod does not transition from 'pending' state

**Comment by cpuguy83** [comment] 2019-03-25 23:39
ACI does not support custom vnet on Windows which is what AKS uses to wire these things up.
Closing since this looks like a dup of #535

Let me know if you think otherwise. Thanks!

**Closed by cpuguy83** 2019-03-25 23:39 UTC
Labels: azure

**Comment by Void-Barrie** [comment] 2019-03-26 15:10
The issue is:

I would expect that windows containers running on ACI instances via Virtual Kublet would be able to resolve K8s service DNS entries.

**Comment by cpuguy83** [comment] 2019-03-26 15:17
Yes, the issue is Windows ACI does not have access to the aks network.
