### ISSUE TITLE
Can't get Load Balancer IP for any service when installed

### ISSUE THREAD

**Issue by AceHack** [virtual-kubelet/virtual-kubelet#41] opened 2017-12-23 06:24 UTC
I followed the updated documentation that was supposed to fix this by creating a more powerful service principle this but I still get this error.

Any service with external IP I try to deploy just stays pending forever

az ad sp create-for-rbac --name sp-arch-aks-aci --role=Contributor --scopes /subscriptions/{subscriptionid}/ --password {password}

When I look at the logs for 

helm install --name vk-linux -f values-linux.yaml "https://github.com/virtual-kubelet/virtual-kubelet/raw/master/charts/virtual-kubelet-0.1.0.tgz"
helm install --name vk-windows -f values-windows.yaml "https://github.com/virtual-kubelet/virtual-kubelet/raw/master/charts/virtual-kubelet-0.1.0.tgz"

--values-linux.yaml--
image:
  repository: microsoft/virtual-kubelet
  tag: latest
  pullPolicy: Always
env:
  azureClientId: {clientid}
  azureClientKey: {clientkey}
  azureTenantId: {tenantid}
  azureSubscriptionId: {subscriptionid}
  aciResourceGroup: rgp-use-arch-aci
  aciRegion: eastus
  nodeName: virtual-kubelet-linux
  nodeTaint: azure.com/aci-linux
  nodeOsType: Linux

--values-windows.yaml--
image:
  repository: microsoft/virtual-kubelet
  tag: latest
  pullPolicy: Always
env:
  azureClientId: {clientid}
  azureClientKey: {clientkey}
  azureTenantId: {tenantid}
  azureSubscriptionId: {subscriptionid}
  aciResourceGroup: rgp-use-arch-aci
  aciRegion: eastus
  nodeName: virtual-kubelet-windows
  nodeTaint: azure.com/aci-windows
  nodeOsType: Windows

/.kube/config 
2017/12/23 06:01:57 Node 'virtual-kubelet-linux' with OS type 'Linux' registered 

/.kube/config 
2017/12/23 06:03:49 Node 'virtual-kubelet-windows' with OS type 'Windows' registered

**Comment by AceHack** [comment] 2017-12-23 06:26
This was my original issue

https://github.com/Azure/AKS/issues/81

**Comment by AceHack** [comment] 2017-12-23 06:28
Here is my new error

Error creating load balancer (will retry): Failed to ensure load balancer for service jenkins/romping-leopard-jenkins: [ensure(jenkins/romping-leopard-jenkins): lb(kubernetes) - failed to ensure host in pool: "compute.VirtualMachinesClient#Get: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code=\"ResourceNotFound\" Message=\"The Resource 'Microsoft.Compute/virtualMachines/virtual-kubelet-linux' under resource group 'MC_rgp-use-arch-aks_aks-use-arch-dev_eastus' was not found.\"", ensure(jenkins/romping-leopard-jenkins): lb(kubernetes) - failed to ensure host in pool: "compute.VirtualMachinesClient#Get: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code=\"ResourceNotFound\" Message=\"The Resource 'Microsoft.Compute/virtualMachines/virtual-kubelet-windows' under resource group 'MC_rgp-use-arch-aks_aks-use-arch-dev_eastus' was not found.\""]

**Comment by robbiezhang** [comment] 2017-12-27 20:31
This is a known issue. The current workaround is to create an external service before install the virtual-kubelet.

I'm looking into the upstream code these days, seems like adding this label

**Comment by bnookala** [comment] 2018-01-11 06:28
Hi @robbiezhang, @rbitia, @ritazh asked me to take this on - just a heads up :D

**Comment by robbiezhang** [comment] 2018-01-11 19:01
@bnookala, thanks for picking this up.

**Comment by rbitia** [comment] 2018-01-18 23:07
Thanks!

**Comment by bnookala** [comment] 2018-01-26 01:20
@rbitia, @robbiezhang sorry for the delay - I'm still making some slow progress on this, and may have something that works for 1.9 clusters by end of week, assuming some manual configuration can be done on the orchestrator itself. 

Is there anything that can be done for < 1.9 clusters? I see that that the `ServiceNodeExclusion`, which should allow for the `alpha.service-controller.kubernetes.io/exclude-balance` label to be respected was only added as an alpha feature in 1.9, so unless it gets cherry picked into a patch release for 1.8, etc, I'm not sure where to start… :)

**Comment by bnookala** [comment] 2018-01-26 05:09
Got it working! There's a few things that needed to be done here:

- 1. Add `alpha.service-controller.kubernetes.io/exclude-balance` as a label to Virtual Kubelet, it's currently an annotation. I'll make a PR for this. 
- 2. Add support for the `ServiceNodeExclusion` flag to acs-engine's kubernetesConfig. 

![screen shot 2018-01-25 at 9 03 39 pm](https://user-images.githubusercontent.com/87996/35425879-63baf38a-0213-11e8-800a-a1ed9f059ca1.png)

**Comment by AceHack** [comment] 2018-01-26 05:27
Does this only work in ACS?  Not AKS?

**Comment by AceHack** [comment] 2018-01-26 05:28
Also, does this mean you cannot load balance over ACI services via a kubernetes load balancer?

**Comment by bnookala** [comment] 2018-01-26 06:18
@AceHack ACS and AKS (managed) are both based upon acs-engine (unmanaged), but currently don't deploy Kubernetes 1.9 clusters (acs-engine can, and both ACS and AKS will eventually).

Kubernetes 1.9 introduced the `ServiceNodeExclusion` flag for the cluster controller, which allows us to fix the behavior you had observed. 

As far as load balancing over ACI - I've not yet tried it out myself. Maybe the others would know more?

**Comment by AceHack** [comment] 2018-01-26 07:13
To my knowledge AKS has no ability to change cluster controller flags and all alpha features are disabled so I don't think this is going to work for AKS.

**Comment by AceHack** [comment] 2018-01-30 00:29
This should not be closed for AKS.  It is managed and you cannot turn on alpha features.

**Comment by AceHack** [comment] 2018-01-30 00:31
Also from my understanding, this would remove ACI from any load balancers.  This does not seem like a workable solution.

**Comment by rbitia** [comment] 2018-02-21 17:55
@AceHack you are correct this isn't the actual solution we are looking for - it's just a workaround. To update everyone we have fixes going upstream in K8 and then fixes in acs-engine itself to enable load-balancing to work across pods in cluster w/ the connector installed w/out any extra tinkering. Once this is enabled in AKS I'll close this issue and open another one for load-balancing across pods in cluster and pods in ACI.

**Comment by pavanagrawal123** [comment] 2018-06-19 03:58
@rbitia have there been any updates in the department of load balancing on AKS w/ an ACI-connector?

**Comment by robbiezhang** [comment] 2018-11-12 19:01
The issue is mitigated in AKS 1.9 cluster

**Closed** 2018-11-12 19:00 UTC
Labels: bug
