### ISSUE TITLE
[Azure] The 'MemoryInGB' request is not specified

### ISSUE THREAD

**Issue by writeameer** [virtual-kubelet/virtual-kubelet#50] opened 2017-12-30 09:11 UTC
Hi there,

Just trying to follow the docs in the README and ran the following command

```
./virtual-kubelet --provider azure
```

I'm getting the following error:

```
2017/12/30 19:59:22 Error creating pod 'kube-svc-redirect-5r8tq': api call to https://management.azure.com/subscriptions/<my subscription id>/resourceGroups/pegasus-aci/providers/Microsoft.ContainerInstance/containerGroups/kube-system-kube-svc-redirect-5r8tq?api-version=2017-12-01-preview: got HTTP response status code 400 error code "ResourceSomeRequestsNotSpecified": The 'MemoryInGB' request is not specified in 'Microsoft.Azure.CloudConsole.Providers.Common.Entities.ComputeResources' in container 'redirector' of contain group 'kube-system-kube-svc-redirect-5r8tq'. It is required since API version '2017-07-01-preview'.
```

Something about the "MemoryInGB" in the container group not being specified and being required in the preview. Any pointers in the right direction would be greatly appreciated.  Thanks so much.

Ameer

**Comment by rbitia** [comment] 2018-01-02 22:26
@neilpeterson that's actually a restriction we have within ACI. You can only deploy up to 20 instances within 5 minutes. We can up the limit for you though! 
@writeameer can you upload your yaml file? I'm guessing you haven't specified a mem/cpu limit for the container but either way we should make some default restrictions for the Azure integration of VK.

Thanks!

**Comment by robbiezhang** [comment] 2018-01-02 22:54
@neilpeterson for your first issue, please use G instead of Gi in the resources.requests field:

>     resources:
>       requests:
>         memory: 1G
>         cpu: 250m

ACI follows the kubernetes [meaning-of-memory](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-memory), but only supports the granularity of 0.1G

**Comment by neilpeterson** [comment] 2018-01-03 00:13
@rbitia - no worries on upping the limit if 20 for me. This seems to only have been an issue during a filed deployment.

As for default capacity values, it looks like some work has gone into this already?

https://github.com/virtual-kubelet/virtual-kubelet/blob/master/providers/azure/aci.go#L85

@robbiezhang - thanks, this fixed my issue.

**Comment by rbitia** [comment] 2018-01-17 21:05
@writeameer Were you able to fix your issue with specifying the resource amounts in the pod spec? If so I'll close this issue! 

Thanks

**Comment by yolo3301** [comment] 2018-01-18 02:14
@writeameer This is actually caused by daemon set. I assume you're using aks, which will create 2 daemon sets by default. I ran into the same issue. A workaround is to specify `--taint` when you start virtual-kubelet. And in your pod template, specify `toleration` for the taint.

**Comment by writeameer** [comment] 2018-01-20 13:44
@rbitia and everyone else - thank you so much. Yup - once resource amounts we specified all was good. Appreciate the help. Awesome project.

**Closed** 2018-01-20 13:44 UTC
Labels: help wanted, question
