### ISSUE TITLE
Pods go in CrashLoopBackOff state

### ISSUE THREAD

**Issue by abizake** [virtual-kubelet/virtual-kubelet#278] opened 2018-07-29 02:57 UTC
---

### Environment summary

Provider (e.g. ACI, AWS Fargate, Hyper) 
ACI

Version (e.g. 0.1, 0.2-beta) 
Latest 

K8s Master Info (e.g. AKS, ACS, Bare Metal, EKS) 
AKS , version 1.10.5

Install Method (e.g. Helm Chart, ) 
Helm (Both Manual and Auto)

### Issue Details  
When I create Virtual Kubelet following the read me file for Azure AKS , the connector pod for both windows and linux go in CrashLoopBackOff state.
Below are the logs which i could fetch :-
time="2018-07-29T02:53:21Z" level=error msg="interface public not found"
/.kube/config
2018/07/29 02:53:21 Reading ACS credential file "/etc/acs/azure.json"
2018/07/29 02:53:21 Load ACS credential file "/etc/acs/azure.json" successfully
2018/07/29 02:53:22 unknown (get configmaps)

**Comment by abizake** [comment] 2018-07-30 15:32
@jeremyrickard  Hello There,
The Cluster has RBAC enabled.

**Comment by jeremyrickard** [comment] 2018-07-30 15:33
@abizake thank you for that confirmation. I'll investigate a little more! 

Thanks again!

**Comment by jeremyrickard** [comment] 2018-07-30 19:32
@abizake This is being caused by the current state of RBAC support in both the AKS VK helm chart and the `az aks install-connector`. In short, when you use the aks vk chart (directly or with `az aks install-connector`), RBAC is being ignored. We're working on a fix to this, will update this when we have a fix ready to go.

**Comment by zodraz** [comment] 2018-08-26 13:46
So how we can fix this at this stage and move one? Could you provide instructions?

**Comment by jeremyrickard** [comment] 2018-08-26 15:11
@zodraz are you still encountering this? 

If you have an older installation, I'd recommend first removing the aci connector. First, ensure you have the latest version of the Azure CLI. 

To remove the connector:

```
az aks remove-connector --name <cluster-name> --group <resource-group>
```

You should then be able to reinstall the connector and everything should work. If you're still experiencing issues after doing that, please share the output from the virtual kubelet pods and describe the pod so we can see any errors.

**Comment by ellesde** [comment] 2018-08-30 19:35
@jeremyrickard 

I have a similar issue in that the vk pod goes into CrashLoopBackOff state, however I don't think it is rbac related.

Installed on AKS (k8s v1.11.2) using azure-cli v2.0.45 and helm v2.10.0.

Below is logs from pod:
```
time="2018-08-30T19:19:19Z" level=error msg="interface public not found"
Flag --taint has been deprecated, Taint key should now be configured using the VK_TAINT_KEY environment variable
/.kube/config
2018/08/30 19:19:19 Reading ACS credential file "/etc/acs/azure.json"
2018/08/30 19:19:19 invalid character 'T' looking for beginning of value
```

Below is describe of pod:
```
Name:               virtual-kubelet-windows-eastus-virtual-kubelet-for-aks-64dcw44n
Namespace:          default
Priority:           0
PriorityClassName:  <none>
Node:               aks-nodepool1-41073875-0/10.240.0.4
Start Time:         Thu, 30 Aug 2018 15:18:53 -0400
Labels:             app=virtual-kubelet-windows-eastus-virtual-kubelet-for-aks
                    pod-template-hash=2082389880
Annotations:        <none>
Status:             Running
IP:                 10.244.1.5
Controlled By:      ReplicaSet/virtual-kubelet-windows-eastus-virtual-kubelet-for-aks-64d67dfdd4
Containers:
  virtual-kubelet-windows-eastus-virtual-kubelet-for-aks:
    Container ID:  docker://627d447b47242464b8d52233946524343baa9fe0a903ac34800241e09f35c53f
    Image:         microsoft/virtual-kubelet:latest
    Image ID:      docker-pullable://microsoft/virtual-kubelet@sha256:a2095ea663560f94fe30d3272ef158fe3f3ba3c1aaea4e6b17ca9d328ad501e0
    Port:          <none>
    Host Port:     <none>
    Command:
      virtual-kubelet
    Args:
      --provider
      azure
      --namespace

      --nodename
      virtual-kubelet-virtual-kubelet-windows-eastus
      --os
      Windows
      --taint
      azure.com/aci
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Thu, 30 Aug 2018 15:20:33 -0400
      Finished:     Thu, 30 Aug 2018 15:20:33 -0400
    Ready:          False
    Restart Count:  4
    Environment:
      KUBELET_PORT:             10250
      ACS_CREDENTIAL_LOCATION:  /etc/acs/azure.json
      AZURE_TENANT_ID:          6c4e2a77-be31-4a8c-abae-6d9c4b988367
      AZURE_SUBSCRIPTION_ID:    b36af595-05a8-47d3-90f2-8eb95a75d68c
      AZURE_CLIENT_ID:
      AZURE_CLIENT_SECRET:      <set to the key 'clientSecret' in secret 'virtual-kubelet-windows-eastus-virtual-kubelet-for-aks'>  Optional: false
      ACI_RESOURCE_GROUP:
      ACI_REGION:               eastus
      APISERVER_CERT_LOCATION:  /etc/virtual-kubelet/cert.pem
      APISERVER_KEY_LOCATION:   /etc/virtual-kubelet/key.pem
      VKUBELET_POD_IP:           (v1:status.podIP)
    Mounts:
      /etc/acs/azure.json from acs-credential (rw)
      /etc/virtual-kubelet from credentials (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from virtual-kubelet-windows-eastus-virtual-kubelet-for-aks-toktccx4 (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  credentials:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  virtual-kubelet-windows-eastus-virtual-kubelet-for-aks
    Optional:    false
  acs-credential:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/kubernetes/azure.json
    HostPathType:  File
  virtual-kubelet-windows-eastus-virtual-kubelet-for-aks-toktccx4:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  virtual-kubelet-windows-eastus-virtual-kubelet-for-aks-toktccx4
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  beta.kubernetes.io/os=linux
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age               From                               Message
  ----     ------     ----              ----                               -------
  Normal   Scheduled  2m                default-scheduler                  Successfully assigned default/virtual-kubelet-windows-eastus-virtual-kubelet-for-aks-64dcw44n to aks-nodepool1-41073875-0
  Normal   Pulled     1m (x4 over 2m)   kubelet, aks-nodepool1-41073875-0  Successfully pulled image "microsoft/virtual-kubelet:latest"
  Normal   Created    1m (x4 over 2m)   kubelet, aks-nodepool1-41073875-0  Created container
  Normal   Started    1m (x4 over 2m)   kubelet, aks-nodepool1-41073875-0  Started container
  Warning  BackOff    1m (x8 over 2m)   kubelet, aks-nodepool1-41073875-0  Back-off restarting failed container
  Normal   Pulling    59s (x5 over 2m)  kubelet, aks-nodepool1-41073875-0  pulling image "microsoft/virtual-kubelet:latest"
```

**Comment by robbiezhang** [comment] 2018-08-30 21:08
@ellesde thanks for reporting. We are investigating the issue.

**Comment by robbiezhang** [comment] 2018-08-31 18:27
@denisborovnev exactly. The issue is in the acs-engine, and cause the malformed file in AKS . The fix will roll out soon.
https://github.com/Azure/acs-engine/pull/3774

**Comment by ellesde** [comment] 2018-09-05 15:34
@robbiezhang Confirming that acs-engine v0.21.2 fixes the issue I had.

**Comment by rbitia** [comment] 2018-11-30 00:46
Closing! Thanks

**Closed by rbitia** 2018-11-30 00:46 UTC
Labels: bug
